version: '3'

services:
  nodeprisma:
    image: postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      POSTGRES_DB: nestjs
      POSTGRES_PASSWORD: testpass123
      POSTGRES_USER: postgres
    ports:
      - '6500:5432'
    volumes:
      - D:\Back-end-project\auth-jwt-nest\db:/var/lib/postgresql/data
